services:
  server_base_image:
    image: server_base_image_postgres
    container_name: server_base_image_postgres
    build:
      context: ./server
      dockerfile: Dockerfile.base

  server_build:
    image: server
    container_name: server
    build:
      context: ./server
    env_file: ./.env
    depends_on:
      - server_base_image

  server:
    image: server_base_image_postgres
    container_name: server
    command: scripts/start_dev.sh
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file: ./.env
    networks:
      - mynetwork
    depends_on:
      - server_base_image
      - database_seed
    volumes:
      - ./server/scripts:/server/scripts:ro
      - ./server/src:/server/src:ro
      - ./server/Cargo.toml:/server/Cargo.toml:ro
      - ./server/Cargo.lock:/server/Cargo.lock:ro

  server_test:
    image: server_base_image_postgres
    container_name: server_test
    command: scripts/test_watch.sh
    env_file: ./.env
    environment:
      - RUST_ENV=test
    networks:
      - mynetwork
    depends_on:
      - server_base_image
      - database_schema
    volumes:
      - ./server/coverage:/server/coverage:rw
      - ./server/scripts:/server/scripts:ro
      - ./server/src:/server/src:ro
      - ./server/Cargo.toml:/server/Cargo.toml:ro
      - ./server/Cargo.lock:/server/Cargo.lock:ro

  database:
    image: postgres:18
    container_name: database
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - mynetwork
    restart: always

  database_schema:
    image: postgres:18
    container_name: database_schema
    command: scripts/database_schema.sh
    env_file: ./.env
    networks:
      - mynetwork
    depends_on:
      - database
    volumes:
      - ./server/scripts:/scripts:ro

  database_seed:
    image: postgres:18
    container_name: database_seed
    command: scripts/database_seed.sh
    env_file: ./.env
    networks:
      - mynetwork
    depends_on:
      - database_schema
    volumes:
      - ./server/scripts:/scripts:ro

  client_build:
    image: client
    container_name: client
    build:
      context: ./client
      args:
        - SERVER_URL=http://localhost:${SERVER_PORT}
    env_file: ./.env

  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    env_file: ./.env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    networks:
      - mynetwork
    volumes:
      - ./client/eslint.config.js:/usr/app/eslint.config.js:ro
      - ./client/index.html:/usr/app/index.html:ro
      - ./client/package-lock.json:/usr/app/package-lock.json:ro
      - ./client/package.json:/usr/app/package.json:ro
      - ./client/public:/usr/app/public:ro
      - ./client/src:/usr/app/src
      - ./client/tsconfig.app.json:/usr/app/tsconfig.app.json:ro
      - ./client/tsconfig.json:/usr/app/tsconfig.json:ro
      - ./client/tsconfig.node.json:/usr/app/tsconfig.node.json:ro
      - ./client/vite.config.ts:/usr/app/vite.config.ts:ro
    restart: always

networks:
  mynetwork:
    driver: bridge
