version: '3.8'

services:
  server_base_image:
    image: server_base_image
    container_name: server_base_image
    build:
      context: ./server
      dockerfile: Dockerfile.base

  server_build:
    image: server
    container_name: server
    build:
      context: ./server
    depends_on:
      - server_base_image

  server:
    image: server_base_image
    container_name: server
    command: scripts/start_dev.sh
    ports:
      - 8080:8080
    environment:
      - DATABASE_URI=mongodb://database:27017
      - DATABASE_NAME=database
    volumes:
      - ./server/.env:/server/.env:ro
      - ./server/Cargo.lock:/server/Cargo.lock:ro
      - ./server/Cargo.toml:/server/Cargo.toml:ro
      - ./server/scripts:/server/scripts:ro
      - ./server/src:/server/src:ro
    depends_on:
      - server_base_image
      - database_seed

  server_test:
    image: server_base_image
    container_name: server_test
    command: scripts/test_watch.sh
    environment:
      - DATABASE_URI=mongodb://database:27017
      - DATABASE_NAME=test_database
    volumes:
      - ./server/.env:/server/.env:ro
      - ./server/Cargo.lock:/server/Cargo.lock:ro
      - ./server/Cargo.toml:/server/Cargo.toml:ro
      - ./server/coverage:/server/coverage:rw
      - ./server/scripts:/server/scripts:ro
      - ./server/src:/server/src:ro
    depends_on:
      - server_base_image
      - database

  database:
    image: mongo:5
    container_name: database
    ports:
      - 27017:27017

  database_seed:
    image: mongo:5
    container_name: database_seed
    command: scripts/database_seed.sh
    environment:
      - DATABASE_HOST=database:27017
      - DATABASE_NAME=database
    depends_on:
      - database
    volumes:
      - ./server/database_seed:/data/seed:ro
      - ./server/scripts:/scripts:ro

  client_base_image:
    image: client_base_image
    container_name: client_base_image
    build:
      context: ./client
      dockerfile: Dockerfile.base

  client_build:
    image: client
    container_name: client
    build:
      context: ./client
      args:
        - SERVER_URL=http://localhost:8080
    depends_on:
      - client_base_image

  client:
    image: client_base_image
    container_name: client
    command: npm start
    working_dir: /client
    ports:
      - 3000:3000
    volumes:
      - ./client/.env.development:/client/.env.development:ro
      - ./client/.eslintrc.js:/client/.eslintrc.js:ro
      - ./client/coverage:/client/coverage:rw
      - ./client/package-lock.json:/client/package-lock.json:ro
      - ./client/package.json:/client/package.json:ro
      - ./client/public:/client/public:ro
      - ./client/src:/client/src:ro
      - ./client/tsconfig.json:/client/tsconfig.json:ro
    depends_on:
      - client_base_image
