[package]
name = "rust_web_server"
version = "0.1.0"
authors = ["Belchior Oliveira <belchior@outlook.com>"]
edition = "2021"

[dependencies]
actix-cors = "0.6.1"
actix-service = "2.0.2"
actix-web = "4.0.1"
base64 = "0.13.0"
deadpool-postgres = "0.10.2"
dotenv = "0.15.0"
env_logger = "0.9.0"
futures = "0.3.17"
futures-util = "0.3.21"
log = "0.4.16"
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
tokio = "1.15.0"
tokio-postgres = "0.7.5"
tokio-stream = "0.1.7"
sql_query_builder = { version = "0.8.4", features = ["postgresql"] }

[dev-dependencies]
pretty_assertions = "1.2.1"
actix-rt = "2.7.0"
