[package]
name = "rust_web_server"
version = "0.1.0"
authors = ["Belchior Oliveira <belchior@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-cors = "0.5.4"
mongodb = "1.2.1"
serde = "1.0.126"
tokio-stream = "0.1.6"
base64 = "0.13.0"
dotenv = "0.15.0"
log = "0.4.14"
env_logger = "0.9.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
cargo-watch = "7.8.0"
