[package]
name = "rust_web_server"
version = "0.1.0"
authors = ["Belchior Oliveira <belchior@outlook.com>"]
edition = "2024"
rust-version = "1.91"

[dependencies]
actix-cors = "0.7.1"
actix-service = "2.0.3"
actix-web = "4.12.1"
base64 = "0.13.0"
dotenv = "0.15.0"
futures = "0.3.31"
futures-util = "0.3.31"
mongodb = "3.4.1"
serde = "1.0.228"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full", "tracing"] }
tokio-stream = "0.1.17"
# used to setup tracing and logs
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json"] }
tracing-actix-web = { version = "0.7.19" }

[dev-dependencies]
pretty_assertions = "1.4.1"
actix-rt = "2.7.0"
